"""STM32N6570 deployment stub.

Provides utilities for preparing models for deployment on the
STM32N6570-DK board (Cortex-M55 + NPU, ~2MB SRAM).

This is a STUB — actual STM32 compilation requires STM32CubeAI or
ST Edge AI Developer Cloud.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass
class STM32DeploymentProfile:
    """Deployment constraints for STM32N6570-DK."""
    max_flash_kb: int = 2048    # 2MB external flash
    max_sram_kb: int = 1536     # ~1.5MB available SRAM
    max_model_kb: int = 512     # Conservative model size limit
    max_inference_ms: int = 100 # Target inference latency
    npu_available: bool = True   # ST Neural-ART NPU
    input_format: str = "uint8"  # Input quantization
    weight_format: str = "int8"  # Weight quantization


def estimate_model_footprint(
    encoder,
    input_size: int = 128,
) -> dict[str, float]:
    """Estimate the model's memory footprint for STM32 deployment.

    Args:
        encoder: PyTorch encoder model.
        input_size: Input resolution.

    Returns:
        Dict with estimated memory requirements.
    """
    import torch

    # Parameter count
    total_params = sum(p.numel() for p in encoder.parameters())
    trainable_params = sum(p.numel() for p in encoder.parameters() if p.requires_grad)

    # Model size (float32 → estimated int8)
    float32_kb = total_params * 4 / 1024
    int8_kb = total_params / 1024

    # Activation memory (rough estimate: largest intermediate tensor)
    encoder.eval()
    with torch.no_grad():
        dummy = torch.zeros(1, 3, input_size, input_size)
        # Track activations
        max_activation_bytes = 0
        hooks = []

        def hook_fn(module, input, output):
            nonlocal max_activation_bytes
            if isinstance(output, torch.Tensor):
                max_activation_bytes = max(max_activation_bytes, output.nelement() * output.element_size())

        for module in encoder.modules():
            hooks.append(module.register_forward_hook(hook_fn))

        encoder(dummy)

        for h in hooks:
            h.remove()

    activation_kb = max_activation_bytes / 1024
    activation_int8_kb = activation_kb / 4  # int8 activations

    profile = STM32DeploymentProfile()

    return {
        "total_params": total_params,
        "trainable_params": trainable_params,
        "model_size_float32_kb": float32_kb,
        "model_size_int8_kb": int8_kb,
        "peak_activation_kb": activation_kb,
        "peak_activation_int8_kb": activation_int8_kb,
        "total_estimated_sram_kb": int8_kb + activation_int8_kb,
        "fits_in_sram": (int8_kb + activation_int8_kb) < profile.max_sram_kb,
        "fits_in_flash": int8_kb < profile.max_flash_kb,
    }


def generate_stm32_stub(
    onnx_path: str | Path,
    output_dir: str | Path,
    project_name: str = "uwcodec_encoder",
) -> Path:
    """Generate a stub C project for STM32CubeAI integration.

    This creates the directory structure and placeholder files needed
    for importing the model into STM32CubeAI.

    Args:
        onnx_path: Path to the ONNX model.
        output_dir: Output directory for the stub project.
        project_name: Name of the STM32 project.

    Returns:
        Path to the generated stub directory.
    """
    output_dir = Path(output_dir)
    project_dir = output_dir / project_name
    project_dir.mkdir(parents=True, exist_ok=True)

    # Create project structure
    (project_dir / "Inc").mkdir(exist_ok=True)
    (project_dir / "Src").mkdir(exist_ok=True)
    (project_dir / "Model").mkdir(exist_ok=True)

    # Copy ONNX model
    import shutil
    onnx_path = Path(onnx_path)
    if onnx_path.exists():
        shutil.copy2(onnx_path, project_dir / "Model" / onnx_path.name)

    # Generate header stub
    header = f"""/* Auto-generated by UWCodec STM32 exporter */
#ifndef {project_name.upper()}_H
#define {project_name.upper()}_H

#include <stdint.h>

/* Model configuration */
#define UWCODEC_INPUT_SIZE     128
#define UWCODEC_INPUT_CHANNELS 3
#define UWCODEC_LATENT_DIM     64
#define UWCODEC_MAX_PAYLOAD    124

/* Initialize the encoder model */
int uwcodec_encoder_init(void);

/* Run encoder inference */
int uwcodec_encoder_run(
    const uint8_t* input_image,   /* RGB input ({project_name}_INPUT_SIZE x {project_name}_INPUT_SIZE x 3) */
    uint8_t* output_payload,      /* Output payload buffer (UWCODEC_MAX_PAYLOAD bytes) */
    uint8_t payload_size          /* Target payload size (64, 96, or 124) */
);

/* Cleanup */
void uwcodec_encoder_deinit(void);

#endif /* {project_name.upper()}_H */
"""
    (project_dir / "Inc" / f"{project_name}.h").write_text(header)

    # Generate source stub
    source = f"""/* Auto-generated by UWCodec STM32 exporter
 *
 * This is a STUB. Actual implementation requires:
 * 1. Import the ONNX model into STM32CubeAI or ST Edge AI Developer Cloud
 * 2. Generate the optimized C code for the target MCU
 * 3. Replace this stub with the generated inference code
 *
 * Target: STM32N6570-DK (Cortex-M55 + Neural-ART NPU)
 */

#include "{project_name}.h"
#include <string.h>

/* TODO: Include STM32CubeAI generated headers */
/* #include "ai_platform.h" */
/* #include "{project_name}_data.h" */

int uwcodec_encoder_init(void) {{
    /* TODO: Initialize AI runtime and load model weights */
    return 0;  /* Success */
}}

int uwcodec_encoder_run(
    const uint8_t* input_image,
    uint8_t* output_payload,
    uint8_t payload_size)
{{
    /* TODO: Run inference through STM32CubeAI runtime */
    /* 1. Preprocess input (normalize, quantize) */
    /* 2. Run encoder forward pass */
    /* 3. Run quantizer to get VQ indices */
    /* 4. Pack indices + metadata into payload */
    memset(output_payload, 0, payload_size);
    return 0;  /* Success */
}}

void uwcodec_encoder_deinit(void) {{
    /* TODO: Cleanup AI runtime resources */
}}
"""
    (project_dir / "Src" / f"{project_name}.c").write_text(source)

    readme = f"""# {project_name} — STM32N6570 Deployment Stub

## Steps to deploy:

1. Open STM32CubeAI or ST Edge AI Developer Cloud
2. Import `Model/{onnx_path.name}` 
3. Select target: STM32N6570-DK
4. Enable INT8 quantization
5. Generate optimized C code
6. Replace the stub in `Src/{project_name}.c` with generated code
7. Build and flash to the board

## Memory Budget:
- Model (INT8): ~100-500 KB
- Activations: ~50-200 KB  
- Total SRAM available: ~1.5 MB
"""
    (project_dir / "README.md").write_text(readme)

    print(f"Generated STM32 deployment stub: {project_dir}")
    return project_dir
